version: '2'
services:
  test:
    build: .
    command: mix test
    environment:
      - MIX_ENV=test
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    volumes:
      - .:/app
    links:
      - postgres

  web:
    build: .
    env_file: .env
    environment:
      - MIX_ENV=dev
    volumes:
      - .:/app
    links:
      - mailcatcher
    ports:
      - "4000:4000"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
