version: '2'
services:
  web:
    image: sergkoba/juggler:latest
    labels:
      io.rancher.container.pull_image: always
    command: mix phoenix.server
    environment:
      - MIX_ENV=prod
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - postgres
      - redis

  postgres:
    image: postgres:latest
    ports:
      - "5432"

  redis:
    image: redis:2.8
    volumes:
      - /data
    ports:
      - "6379"
