version: '2'
services:
  web:
    build: .
    env_file: .env
    command: mix phoenix.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "4000:4000"
    links:
      - postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432"
