version: '2'
services:
  test:
    build: .
    command: mix test
    environment:
      - MIX_ENV=test
      - PG_HOST=postgres
      - PG_USERNAME=postgres
    volumes:
      - .:/app
    links:
      - postgres

  web:
    links:
      - mailcatcher

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
